from enum import Enum


class SynsetRelationType(Enum):
    Hypernym = "Hypernym"
    Hyponym = "Hyponym"
    Instance_hypernym = "Instance_hypernym"
    Instance_hyponym = "Instance_hyponym"
    Part_holonym = "Part_holonym"
    Part_meronym = "Part_meronym"
    Member_holonym = "Member_holonym"
    Member_meronym = "Member_meronym"
    Substance_holonym = "Substance_holonym"
    Substance_meronym = "Substance_meronym"
    Portion_holonym = "Portion_holonym"
    Portion_meronym = "Portion_meronym"
    Domain = "Domain"
    Is_Domain_of = "Is_Domain_of"
    Antonym = "Antonym"
    Is_Agent_of = "Is_Agent_of"
    Agent = "Agent"
    Is_Caused_by = "Is_Caused_by"
    Cause = "Cause"
    Is_Instrument_of = "Is_Instrument_of"
    Instrument = "Instrument"
    Is_Entailed_by = "Is_Entailed_by"
    Entailment = "Entailment"
    Location = "Location"
    Is_Location_of = "Is_Location_of"
    Has_Salient_defining_feature = "Has_Salient_defining_feature"
    Salient_defining_feature = "Salient_defining_feature"
    Is_Attribute_of = "Is_Attribute_of"
    Attribute = "Attribute"
    Unit = "Unit"
    Has_Unit = "Has_Unit"
    Related_to = "Related_to"
    Is_Patient_of = "Is_Patient_of"
    Patient = "Patient"
